package com.bookify.backendbookify_saas.repositories;

import com.bookify.backendbookify_saas.models.entities.StaffAvailability;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
public interface StaffAvailabilityRepository extends JpaRepository<StaffAvailability, Long> {

    /**
     * Find availability by staff and date
     */
    Optional<StaffAvailability> findByStaff_IdAndDate(Long staffId, LocalDate date);

    /**
     * Check if availability exists for staff and date
     */
    boolean existsByStaff_IdAndDate(Long staffId, LocalDate date);

    /**
     * Delete all auto-generated (not user-edited) availabilities for a staff member in a date range
     */
    @Modifying
    @Query("DELETE FROM StaffAvailability sa WHERE sa.staff.id = :staffId AND sa.date BETWEEN :startDate AND :endDate AND sa.userEdited = false")
    void deleteAutoGeneratedInRange(@Param("staffId") Long staffId, @Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);

    /**
     * Find all availabilities for a specific business on a specific date.
     * Uses native query to join staff table and filter by business_id.
     */
    @Query(value = "SELECT sa.* FROM staff_availabilities sa " +
                   "INNER JOIN staff s ON sa.staff_id = s.id " +
                   "WHERE s.business_id = :businessId AND sa.date = :date",
           nativeQuery = true)
    List<StaffAvailability> findByBusinessIdAndDate(@Param("businessId") Long businessId, @Param("date") LocalDate date);

    /**
     * Count availabilities for a business on a date (native) - helpful for debugging parameter binding issues
     */
    @Query(value = "SELECT COUNT(1) FROM staff_availabilities sa INNER JOIN staff s ON sa.staff_id = s.id WHERE s.business_id = :businessId AND sa.date = :date", nativeQuery = true)
    int countByBusinessIdAndDate(@Param("businessId") Long businessId, @Param("date") LocalDate date);

    /**
     * Fetch all availabilities for a business between two dates in a single query.
     * This avoids issuing one query per date (reduces load and logs).
     */
    @Query(value = "SELECT sa.* FROM staff_availabilities sa INNER JOIN staff s ON sa.staff_id = s.id WHERE s.business_id = :businessId AND sa.date BETWEEN :start AND :end", nativeQuery = true)
    List<StaffAvailability> findByBusinessIdAndDateRange(@Param("businessId") Long businessId, @Param("start") LocalDate start, @Param("end") LocalDate end);

    /**
     * New explicit JPQL query: fetch availabilities for a staff between two dates (inclusive).
     */
    @Query("SELECT sa FROM StaffAvailability sa WHERE sa.staff.id = :staffId AND sa.date BETWEEN :start AND :end")
    List<StaffAvailability> findByStaffIdAndDateRange(@Param("staffId") Long staffId, @Param("start") LocalDate start, @Param("end") LocalDate end);

    /**
     * New derived query: find by staff id between dates
     */
    List<StaffAvailability> findByStaff_IdAndDateBetween(Long staffId, LocalDate start, LocalDate end);

    /**
     * Bulk update: set status to CLOSED for rows matching business and date condition (Sunday OR specified day)
     * Implemented in JPQL using FUNCTION to call the DB DAYOFWEEK.
     */
    @Modifying(clearAutomatically = true)
    @Query("UPDATE StaffAvailability sa SET sa.status = :status, sa.updatedAt = CURRENT_TIMESTAMP " +
           "WHERE sa.staff.business.id = :businessId AND sa.date BETWEEN :start AND :end " +
           "AND (FUNCTION('DAYOFWEEK', sa.date) = :dow OR FUNCTION('DAYOFWEEK', sa.date) = 1) " +
           "AND sa.userEdited = false AND sa.status <> :status")
    int bulkUpdateStatusToClosedForBusinessInRange(@Param("businessId") Long businessId, @Param("start") LocalDate start, @Param("end") LocalDate end, @Param("dow") int mysqlDayOfWeek, @Param("status") String status);

    /**
     * Bulk update: set status to AVAILABLE for rows matching business and date condition (not Sunday AND not the weekend day)
     */
    @Modifying(clearAutomatically = true)
    @Query("UPDATE StaffAvailability sa SET sa.status = :status, sa.updatedAt = CURRENT_TIMESTAMP " +
           "WHERE sa.staff.business.id = :businessId AND sa.date BETWEEN :start AND :end " +
           "AND (FUNCTION('DAYOFWEEK', sa.date) <> :dow AND FUNCTION('DAYOFWEEK', sa.date) <> 1) " +
           "AND sa.userEdited = false AND sa.status <> :status")
    int bulkUpdateStatusToAvailableForBusinessInRange(@Param("businessId") Long businessId, @Param("start") LocalDate start, @Param("end") LocalDate end, @Param("dow") int mysqlDayOfWeek, @Param("status") String status);

    /**
     * NEW: Return the maximum date available for a specific staff (used to build the calendar end date).
     */
    @Query("SELECT MAX(sa.date) FROM StaffAvailability sa WHERE sa.staff.id = :staffId")
    LocalDate findMaxDateByStaffId(@Param("staffId") Long staffId);
}
